### PR TITLE
fix(Field.Currency): handle big numbers

### LINKED ISSUE #3124: bug(Field.Currency): strange behaviour when entering big/large numbers
## 🐛 Bug Report

When entering values in the number field, it suddenly changes values.

All I do is entering the value `8`, many times.

Video:

https://github.com/dnbexperience/eufemia/assets/1359205/9ec77cf7-a442-4778-bc90-64f6c16150d0

## To Reproduce

Go to the [following example in our docs](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/Currency/#empty):
- Enter `8` many many times
- Then just observe what happens after entering `8` for the 17th time(input changes from `88888888888888888` to `88888888888888900`) and 22th time pressing 8(input changes to `8,888888888888` and onChange returns `8.88888888888889e+21`).

## Expected behavior

I expect it to behave as a regular input field, see the following [CSB](https://codesandbox.io/p/sandbox/boring-sky-kvqgxv?file=%2Fsrc%2FApp.tsx), and video(left is input type `string` and right is input type `number`):

https://github.com/dnbexperience/eufemia/assets/1359205/52788f63-a4f1-44e6-82c0-d6f2788cfd2d

### PR DESCRIPTION
**Pull request by tujoworker**
- Fixes #3124
- Relies on PR #3185 and will be rebased from main later: ✅

### CODE REVIEW

File: packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx [hunk 1]
```diff
@@ -104,14 +104,32 @@ function NumberComponent(props: Props) {
...
+
+      return event?.numberValue
     },
     [props.emptyValue]
   )
+  const transformValue = useCallback(
+    (value: number, currentValue: number) => {
+      if (
+        value > Number.MAX_SAFE_INTEGER ||
+        value < -Number.MAX_SAFE_INTEGER
```
Comment (snorrekim) [inline packages/dnb-eufemia/src/extensions/forms/Field/Number/Number.tsx:124]: This could better just be Number.MIN_SAFE_INTEGER

**Review by joakbjerk — APPROVED** [review]
🔥
