### PR TITLE
fix(Forms): correctly report error during Wizard step navigation with async event handler or field validator

### LINKED ISSUE #4892: Form validation: Validation messages appear immediately after navigation to Step when using `onStepChange`
## 🐛 Bug Report
After upgrade to latest version of Eufemia (10.69.1), validation errors now appear immediately after navigating to the next step in Wizard.

See video:

https://github.com/user-attachments/assets/a35b6729-c2f1-4c62-b602-741cbd57751e

## To Reproduce

I haven't been able to reproduce the issue in a CSB, but you can pull the latest version of our repo and run it locally to see the issue:

https://gitlab.tech.dnb.no/dnb/dcf/dnb-web-codd-apps

Hint: commenting out the `onStepChange` hook [in our project ](https://gitlab.tech.dnb.no/dnb/dcf/dnb-web-codd-apps/-/blob/main/apps/dkt-as/src/pages/Form/WizardContainer.tsx#L70)fixes the issue. We use this to save information to the backend on every step.

Here's the CSB where I tried unsuccessfully to reproduce the error. But it can still be used as a starting point to figuring it out: https://codesandbox.io/p/sandbox/onstepchange-validation-error-vv2733

## Expected behavior

Should expect the validation to appear only after the user has clicked the next step on an invalid form, not immediately when opening a new step and displaying the form for the first time.

## Run `npx envinfo`

Paste the results here:

```bash
  System:
    OS: macOS 15.3.2
    CPU: (11) arm64 Apple M3 Pro
    Memory: 94.78 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.13.1 - ~/.nvm/versions/node/v22.13.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.13.1/bin/yarn
    npm: 10.9.2 - ~/.nvm/versions/node/v22.13.1/bin/npm
    pnpm: 9.14.2 - ~/.nvm/versions/node/v22.13.1/bin/pnpm
  Managers:
    Homebrew: 4.4.20 - /opt/homebrew/bin/brew
    pip3: 24.2 - ~/miniconda3/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 17.0.0 - /usr/bin/gcc
    Git: 2.45.1 - /opt/homebrew/bin/git
    Clang: 17.0.0 - /usr/bin/clang
    Curl: 8.7.1 - /usr/bin/curl
    OpenSSL: 3.0.15 - /Users/torrytufteland/miniconda3/bin/openssl
  Servers:
    Apache: 2.4.62 - /usr/sbin/apachectl
  Virtualization:
    Docker: 27.3.1 - /usr/local/bin/docker
    Docker Compose: 2.30.3 - /usr/local/bin/docker-compose
  IDEs:
    IntelliJ: 2024.3.5
    VSCode: 1.98.2 - /usr/local/bin/code
    Vim: 9.1 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.4 - /Users/torrytufteland/.sdkman/candidates/java/current/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python: 3.12.7 - /Users/torrytufteland/miniconda3/bin/python
    Python3: 3.12.7 - /Users/torrytufteland/miniconda3/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.45.3 - /Users/torrytufteland/miniconda3/bin/sqlite3
  Browsers:
    Chrome: 134.0.6998.167
    Edge: 134.0.3124.95
    Safari: 18.3.1
```

## Eufemia Version
10.69.1

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #4892

### CODE REVIEW

File: packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts [hunk 1]
```diff
@@ -952,12 +952,6 @@ export default function useFieldProps<Value, EmptyValue, Props>(
       setFieldErrorDataContext?.(identifier, error)
       setFieldErrorBoundary?.(identifier, error)
 
-      setFieldErrorWizard?.(
-        wizardIndex,
-        identifier,
-        handleFieldAsVisible !== false ? Boolean(error) : undefined
-      )
-
```
Comment (tujoworker) [inline packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts:960]: I'm pretty sure calling this method causes the issue, even if the reproduction linked in the issue does not fully reproduce the issue in the production code.

This PR has now a different and better solution for handling error reporting for when a validator or event handler is of `async` nature.

**Review by langz — APPROVED** [review]
🤞
