### PR TITLE
fix(NumberFormat): render properly when `sv-SE` locale is given

### LINKED ISSUE #4753: sv-SE translation is not working for NumberFormat component
## 🐛 Bug Report

Change components language to Svenska.
Try to visit this page, it breaks.

https://eufemia.dnb.no/uilib/components/number-format/

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #4753

### CODE REVIEW

**Review by langz — APPROVED** [review]

File: packages/dnb-eufemia/src/components/number-format/NumberUtils.js [hunk 1]
```diff
@@ -309,7 +309,7 @@ export const format = (
     }
 
     if (value === 'invalid') {
-      aria = locales[locale].NumberFormat.not_available || 'N/A'
+      aria = locales[locale]?.NumberFormat.not_available || 'N/A'
```
Comment (langz) [inline packages/dnb-eufemia/src/components/number-format/NumberUtils.js:312]: Looks like a decent fix 👏 
But as far as I understand this, then this translation is not in use https://github.com/dnbexperience/eufemia/blob/8d9e2624e0aeccc74f5b70860a39f1e6d2b18e15/packages/dnb-eufemia/src/shared/locales/sv-SE.ts#L96

as `locales from '../../shared/locales'` will never have the `sv-SE` translations, but only for `nb-NO` and `en-GB`, which makes the translation https://github.com/dnbexperience/eufemia/blob/8d9e2624e0aeccc74f5b70860a39f1e6d2b18e15/packages/dnb-eufemia/src/shared/locales/sv-SE.ts#L96 dead code? As it will never be used? 🤔
