### PR TITLE
fix(Forms): ensure correct sorting in Field.SelectCountry

### LINKED ISSUE #4195: Sorting of countries - why is Åland Islands listed/sorted side by side with the countries starting with A?
## 🐛 Bug Report

Why is Åland Islands listed/sorted side by side with the countries starting with A?
Shouldn't it be in the end of the sorting, as Å is the last letter in the norwegian alphabet?

https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/SelectCountry/demos/

image

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #4195

### CODE REVIEW

File: packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx [hunk 1]
```diff
@@ -305,7 +305,7 @@ export function getCountryData({
         }
       }
 
-      return String(a[lang])?.localeCompare?.(b[lang])
+      return String(a[lang])?.localeCompare?.(b[lang], 'nb') // Always sort by nb, because åøæ (for Åland) is not in the en alphabet
```
Comment (langz) [inline packages/dnb-eufemia/src/extensions/forms/Field/SelectCountry/SelectCountry.tsx:308]: 🤝

**Review by langz — APPROVED** [review]
