### PR TITLE
fix(Forms): ensure Iterate.Array schema validation

### LINKED ISSUE #4956: Client side validation is not being applied in latest eufemia version when deleting an element
## 🐛 Bug Report

We are facing an issue where client side validation is not being applied in the latest Eufemia version when deleting elements from our form.
I am unable to reproduce the issue directly in the codesandbox, but I have linked our repo below. 

## To Reproduce

[Validation not working as expected](https://github.com/user-attachments/assets/4b72ef4a-bd23-484a-b263-f5b54eac01dc)

## Expected behavior

[Validation working as expected](https://github.com/user-attachments/assets/a463e5a5-b4cd-478b-8520-3eb8979ff942)

### Link to our repo
https://gitlab.tech.dnb.no/dnb/dcf/dnb-web-codd-apps

## Eufemia Version
Version with validation issue:
Eufemia: 10.70.0
Eufemia CSS: 10.65.1

Version without validation issue:
Eufemia: 10.68.1
Eufemia CSS: 10.65.1

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #4956
PR [Preview](https://eufemia-git-fix-iterate-schema-minitems-eufemia.vercel.app/uilib/extensions/forms/Iterate/Array/#minium-one-item).

### CODE REVIEW

File: packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts [hunk 1]
```diff
@@ -631,7 +631,7 @@ export default function useFieldProps<Value, EmptyValue, Props>(
     }
 
     const hasError = Boolean(localErrorRef.current)
-    revealErrorRef.current = hasError
+    revealErrorRef.current = true
```
Comment (langz) [inline packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts:634]: Is this change intended/correct?

Comment (langz) [reply packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts:634]: Hehe, yeah, a bit silly question, as that's the only code actually changed. But I assumed it would make sense for it to stay as it was before🤣

**Review by langz — APPROVED** [review]

File: packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts (hunk 1 above)
Comment (tujoworker) [reply packages/dnb-eufemia/src/extensions/forms/hooks/useFieldProps.ts:634]: Me too. But we had it set to `true` before. [Here](https://github.com/dnbexperience/eufemia/pull/4786/files#r2054011414) we changed it.
